CONV := ./makepng
PLAIN := icon-gen-512x512.png icon-gen-144x144.png \
			icon-gen-96x96.png icon-gen-72x72.png \
			icon-gen-48x48.png icon-gen-36x36.png
LOVETRUE := lovetrue-gen-512x512.png lovetrue-gen-144x144.png \
			lovetrue-gen-96x96.png lovetrue-gen-72x72.png \
			lovetrue-gen-48x48.png lovetrue-gen-36x36.png
LOVEFALSE := lovefalse-gen-512x512.png lovefalse-gen-144x144.png \
			lovefalse-gen-96x96.png lovefalse-gen-72x72.png \
			lovefalse-gen-48x48.png lovefalse-gen-36x36.png
LOVEUNKNOWN := loveunknown-gen-512x512.png loveunknown-gen-144x144.png \
				loveunknown-gen-96x96.png loveunknown-gen-72x72.png \
				loveunknown-gen-48x48.png loveunknown-gen-36x36.png
TAG := tag-gen-512x512.png tag-gen-144x144.png \
				tag-gen-96x96.png tag-gen-72x72.png \
				tag-gen-48x48.png tag-gen-36x36.png

all : plain lovetrue lovefalse loveunknown tag
plain : $(PLAIN)
lovetrue : $(LOVETRUE)
lovefalse : $(LOVEFALSE)
loveunknown : $(LOVEUNKNOWN)
tag : $(TAG)

icon-gen-512x512.png : icon.svg
	$(CONV) icon-gen-512x512.png
	optipng -q generated/icon-gen-512x512.png
icon-gen-144x144.png : icon.svg
	$(CONV) icon-gen-144x144.png
	optipng -q generated/icon-gen-144x144.png
icon-gen-96x96.png : icon.svg
	$(CONV) icon-gen-96x96.png
	optipng -q generated/icon-gen-96x96.png
icon-gen-72x72.png : icon.svg
	$(CONV) icon-gen-72x72.png
	optipng -q generated/icon-gen-72x72.png
icon-gen-48x48.png : icon.svg
	$(CONV) icon-gen-48x48.png
	optipng -q generated/icon-gen-48x48.png
icon-gen-36x36.png : icon.svg
	$(CONV) icon-gen-36x36.png
	optipng -q generated/icon-gen-36x36.png

lovetrue-gen-512x512.png : lovetrue.svg
	$(CONV) lovetrue-gen-512x512.png
	optipng -q generated/lovetrue-gen-512x512.png
lovetrue-gen-144x144.png : lovetrue.svg
	$(CONV) lovetrue-gen-144x144.png
	optipng -q generated/lovetrue-gen-144x144.png
lovetrue-gen-96x96.png : lovetrue.svg
	$(CONV) lovetrue-gen-96x96.png
	optipng -q generated/lovetrue-gen-96x96.png
lovetrue-gen-72x72.png : lovetrue.svg
	$(CONV) lovetrue-gen-72x72.png
	optipng -q generated/lovetrue-gen-72x72.png
lovetrue-gen-48x48.png : lovetrue.svg
	$(CONV) lovetrue-gen-48x48.png
	optipng -q generated/lovetrue-gen-48x48.png
lovetrue-gen-36x36.png : lovetrue.svg
	$(CONV) lovetrue-gen-36x36.png
	optipng -q generated/lovetrue-gen-36x36.png

lovefalse-gen-512x512.png : lovefalse.svg
	$(CONV) lovefalse-gen-512x512.png
	optipng -q generated/lovefalse-gen-512x512.png
lovefalse-gen-144x144.png : lovefalse.svg
	$(CONV) lovefalse-gen-144x144.png
	optipng -q generated/lovefalse-gen-144x144.png
lovefalse-gen-96x96.png : lovefalse.svg
	$(CONV) lovefalse-gen-96x96.png
	optipng -q generated/lovefalse-gen-96x96.png
lovefalse-gen-72x72.png : lovefalse.svg
	$(CONV) lovefalse-gen-72x72.png
	optipng -q generated/lovefalse-gen-72x72.png
lovefalse-gen-48x48.png : lovefalse.svg
	$(CONV) lovefalse-gen-48x48.png
	optipng -q generated/lovefalse-gen-48x48.png
lovefalse-gen-36x36.png : lovefalse.svg
	$(CONV) lovefalse-gen-36x36.png
	optipng -q generated/lovefalse-gen-36x36.png

loveunknown-gen-512x512.png : loveunknown.svg
	$(CONV) loveunknown-gen-512x512.png
	optipng -q generated/loveunknown-gen-512x512.png
loveunknown-gen-144x144.png : loveunknown.svg
	$(CONV) loveunknown-gen-144x144.png
	optipng -q generated/loveunknown-gen-144x144.png
loveunknown-gen-96x96.png : loveunknown.svg
	$(CONV) loveunknown-gen-96x96.png
	optipng -q generated/loveunknown-gen-96x96.png
loveunknown-gen-72x72.png : loveunknown.svg
	$(CONV) loveunknown-gen-72x72.png
	optipng -q generated/loveunknown-gen-72x72.png
loveunknown-gen-48x48.png : loveunknown.svg
	$(CONV) loveunknown-gen-48x48.png
	optipng -q generated/loveunknown-gen-48x48.png
loveunknown-gen-36x36.png : loveunknown.svg
	$(CONV) loveunknown-gen-36x36.png
	optipng -q generated/loveunknown-gen-36x36.png

tag-gen-512x512.png : tag.svg
	$(CONV) tag-gen-512x512.png
	optipng -q generated/tag-gen-512x512.png
tag-gen-144x144.png : tag.svg
	$(CONV) tag-gen-144x144.png
	optipng -q generated/tag-gen-144x144.png
tag-gen-96x96.png : tag.svg
	$(CONV) tag-gen-96x96.png
	optipng -q generated/tag-gen-96x96.png
tag-gen-72x72.png : tag.svg
	$(CONV) tag-gen-72x72.png
	optipng -q generated/tag-gen-72x72.png
tag-gen-48x48.png : tag.svg
	$(CONV) tag-gen-48x48.png
	optipng -q generated/tag-gen-48x48.png
tag-gen-36x36.png : tag.svg
	$(CONV) tag-gen-36x36.png
	optipng -q generated/tag-gen-36x36.png
clean : 
	rm -rf generated/*

