#!/usr/bin/env python
import os
import sys

targetName = sys.argv[1]
tokens = targetName.split(".")[0].split("-")
                      
resolution = tokens[-1].split("x")

sourceimage = "%s.svg" % tokens[0]

cmdList = ["inkscape"]
cmdList.append("--without-gui")
cmdList.append("--file=%s" % sourceimage)
cmdList.append("--export-png=%s" % os.path.join("generated", targetName))
if int(resolution[0]) != 512 or int(resolution[1]) != 512:
    cmdList.append("--export-width=%s" % resolution[0])
    cmdList.append("--export-height=%s" % resolution[1])


cmd = " ".join(cmdList)
print "About to run: '%s'" % cmd
os.system(cmd)
